{{- if include "emeland.gitsensorCreateDeployKeySecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emeland.gitsensorDeployKeySecretName" . }}
  labels:
    {{- include "emeland.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_ed25519: |
    {{- .Values.gitsensor.deployKey.privateKey | nindent 4 }}
  id_ed25519.pub: {{ .Values.gitsensor.deployKey.publicKey | quote }}
{{- end }}
