{{- if .Values.filter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emeland.fullname" . }}-filter
  labels:
    {{- include "emeland.labels" . | nindent 4 }}
    component: filter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.filter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "emeland.selectorLabels" . | nindent 4 }}
    component: filter

---

{{- end }}
{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emeland.fullname" . }}-server
  labels:
    {{- include "emeland.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "emeland.selectorLabels" . | nindent 4 }}
    component: server
{{- end }}
