apiVersion: v2
name: emeland-crd
description: Parent chart for the CRDs required by the EmELand Kubernetes sensor.

type: application

version: 0.3.0

appVersion: "0.9.0"

dependencies:
  - name: modelsrv-k8s-crd
    version: 0.6.0
    repository: "oci://ghcr.io/emeland-io/charts"
