apiVersion: v2
name: emeland
description: Production Helm chart for deploying the EmELand stack on Kubernetes.

type: application

version: 0.3.0

appVersion: "0.9.0"

dependencies:
  - name: modelsrv-k8s-crd
    version: 0.6.0
    repository: "oci://ghcr.io/emeland-io/charts"
    condition: modelsrv-k8s-sensor.enabled

  - name: modelsrv-k8s-sensor
    version: 0.6.0
    repository: "oci://ghcr.io/emeland-io/charts"
    condition: modelsrv-k8s-sensor.enabled
